name: Voyant
services:
  mongodb:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  app:
    image: oven/bun:1.2.2
    container_name: app_container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "apt-get update && apt-get install -y chromium && bun install && bun run dev"
    depends_on:
      - mongodb
    environment:
      DB_URL: "mongodb://root:example@mongodb:27017"
      CHROME_PATH: "/usr/bin/chromium"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongodb_data:
